version: '3.4'

services:
  core.api:
    image: ${DOCKER_REGISTRY-}pushcoreapi
    build:
      context: .
      dockerfile: Services/Core/Core.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "49301:49301"
    depends_on:
      - rabbitmq
      - db
    networks:
      - app_network

  db:
    container_name: pushdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 1qaz@WSX3edc
      ACCEPT_EULA: Y
      MSSQL_TCP_PORT: 50433
    volumes:
      - "./App_Data/data/:/var/opt/mssql/data/"
      - "./App_Data/log/:/var/opt/mssql/log/"
      - "./App_Data/secrets/:/var/opt/mssql/secrets/"
    ports:
      - "60733:50433"
    networks:
      - app_network

  rabbitmq:
    container_name: pushrabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  bb:
   container_name: busybox
   image: busybox:latest
   command: sleep 3000
   networks:
      - app_network
networks:
  app_network:
    driver: bridge